config/routes.rb
Rails.application.routes.draw do
  root to: 'page#about'
  get 'page/about'
  get 'page/contact'
  resources :portfolios
  resources :skills, except: [:show]
  resources :memos
  resources :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates_presence_of :title, :source, :body
  default_scope { order(created_at: :desc) }
  scope :months_ago, -> (months) { where(created_at: months.month.ago..(months-1).month.ago) }
end

app/models/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern
    def self.image_generator(height:, width:)
      "http://via.placeholder.com/#{width}x#{height}"
    end
end

app/models/memo.rb
class Memo < ApplicationRecord
  validates_presence_of :title, :body
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  include Placeholder
  after_initialize :set_defaults
  validates_presence_of :title, :subtitle, :body

  def set_defaults
    self.main_img ||= Placeholder.generate_image(width: 600, height: 400)
    self.thumb_img ||= Placeholder.generate_image(width: 350, height: 200)
  end

end

app/models/skill.rb
class Skill < ApplicationRecord
  include Placeholder
  after_initialize :set_defaults
  validates_presence_of :title, :percent
  validates :percent, numericality: { only_integer: true, less_than_or_equal_to: 100 }
  default_scope { order(created_at: :asc) }

  def set_defaults
    self.badge ||= Placeholder.image_generator(width: 81, height: 100)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  layout 'blog', only: [:index, :show]
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @all_blogs = Blog.all
    @blogs = Blog.page(params[:page])
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @all_blogs = Blog.all
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }

      else
        format.html { render :new }

      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }

      else
        format.html { render :edit }

      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully deleted.' }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :source, :body)
    end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  layout 'memo', only: [:index]
  before_action :set_memo, only: [:edit,:update,:destroy, :show]
  def index
    @memos = Memo.all
  end
  def new
    @memo = Memo.new
  end
  def show
  end
  def create
    @memo = Memo.new(memo_params)
    if @memo.save
      redirect_to memos_path
    else
      render :new
    end
  end
  def edit
  end
  def update
    if @memo.update(memo_params)
      redirect_to memos_path
    else
      render :edit
    end
  end
  def destroy
    @memo.delete
    redirect_to memos_path
  end
  private
  def memo_params
    params.require(:memo).permit(:title, :body)
  end
  def set_memo
    @memo = Memo.find(params[:id])
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  layout 'home'
  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout 'album', only: [:index]
  before_action :set_portfolio, only: [:edit, :update, :destroy, :show]
  def index
    @portfolios = Portfolio.all
  end
  def new
    @portfolio = Portfolio.new
  end
  def create
    @portfolio = Portfolio.new(portfolio_params)
    if @portfolio.save
      redirect_to portfolios_path, notice: "New portfolio created"
    else
      render :new, alert: "Something wrong"
    end
  end
  def show
  end
  def edit
  end
  def update
    if @portfolio.update(portfolio_params)
      redirect_to portfolios_path, notice: "Portfolio updated"
    else
      render :edit, alert: "Something wrong"
    end
  end
  def destroy
    @portfolio.delete
    redirect_to portfolios_path
  end
private
  def portfolio_params
    params.require(:portfolio).permit(:title, :subtitle, :body)
  end
  def set_portfolio
    @portfolio = Portfolio.find(params[:id])
  end
end

app/controllers/skills.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:edit, :udate, :destroy]
  def index
    @skills = Skill.all
  end
  def new
    @skill = Skill.new
  end
  def create
    @skill = Skill.new(skill_params)
    if @skill.save
      redirect_to skills_path
    else
      render :new
    end
  end
  def edit
  end
  def update
    if @skill.update
      redirect_to skills_path
    else
      render :edit
    end
  end
  def destroy
    @skill.delete
    redirect_to skills_path
  end
  private
  def set_skill
    @skill = Skill.find(params[:id])
  end
  def skill_params
    params.require(:skill).permit(:title, :badge, :percent)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:edit, :udate, :destroy]
  def index
    @skills = Skill.all
  end
  def new
    @skill = Skill.new
  end
  def create
    @skill = Skill.new(skill_params)
    if @skill.save
      redirect_to skills_path
    else
      render :new
    end
  end
  def edit
  end
  def update
    if @skill.update
      redirect_to skills_path
    else
      render :edit
    end
  end
  def destroy
    @skill.delete
    redirect_to skills_path
  end
  private
  def set_skill
    @skill = Skill.find(params[:id])
  end
  def skill_params
    params.require(:skill).permit(:title, :badge, :percent)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def year
    Time.current.year
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def month_human_name(month)
    case month
    when 1
      'Январь'
    when 2
      'Февраль'
    when 3
      'Март'
    when 4
      'Апрель'
    when 5
      'Май'
    when 6
      'Июнь'
    when 7
      'Июль'
    when 8
      'Август'
    when 9
      'Сентябрь'
    when 10
      'Октябрь'
    when 11
      'Ноябрь'
    else
      'Декабрь'
    end
  end

end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_blog.html.erb
    <h2 class="blog-post-title"><%= blog.title %></h2>
    <p class="blog-post-meta"><%= time_ago_in_words(blog.created_at) %> ago</p>
    <p><%= blog.source %></p>
    <hr>

    <%= truncate(blog.body, length: 300) { link_to 'Читать дальше', blog_path(blog)} %>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :Title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :Source %>
    <%= form.text_area :source, rows: 5, cols: 75 %>
  </div>
  <div>
    <%= form.label :Body %>
    <%= form.text_area :body, rows: 15, cols: 75 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<%= render @blogs %>
<p>
<nav class="blog-pagination">
  <%= link_to_next_page @blogs, 'Ранее', class: "btn btn-outline-primary" %>
  <%= link_to_prev_page @blogs, 'Позднее', class: "btn btn-outline-primary" %>
</nav>
</p>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
    <h2 class="blog-post-title"><%= @blog.title %></h2>
    <p class="blog-post-meta">
      <%= time_ago_in_words(@blog.created_at) %> ago
    </p>
    <p>
      <%= @blog.source %>
    </p>
    <hr>
    <%= @blog.body %>
    <p>
    <nav class="blog-pagination">
    <%= link_to 'Назад', blogs_path, class: "btn btn-outline-primary" %>
    </nav>
  </p>

app/views/layouts/album.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="path/to/swiper.min.css"
    <title>Портфолио</title>
  </head>
  <body>
    <script src="path/to/swiper.min.js"></script>
    <div class="swiper-container">
    <%= render 'shared/nav_bar' %>
    <main role="main">
      <div class="album py-5">
        <div class="container">
          <div class="row">
            <%= render @portfolios %>
          </div>
        </div>
      </div>
    </main>
    <footer class="footer bg-dark">
      <%= render 'shared/footer' %>
    </footer>
  </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Блог и портфолио</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav_bar' %>
      <div class="container">
        <%= yield %>
      </div>
      <footer class="footer bg-dark">
        <%= render 'shared/footer', location: 'bottom'%>
      </footer>
  </body>
</html>

app/views/layouts/blog.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="path/to/swiper.min.css">
    <title>Блог</title>
  </head>

  <body>
    <div class="swiper-container">
    <div class="swiper-button-next">></div>
    <div class="swiper-button-prev"><</div>
    <script src="path/to/swiper.min.js"></script>
    <script>
      var swiper = new Swiper('.swiper-container', {
        navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
        },
      });
</script>
    <%= render 'shared/nav_bar' %>
    <main role="main">
      <div class="container">
        <div class="row">
          <div class="col-md-8 blog-main">
            <div class="blog-post">
              <%= yield %>
            </div>
          </div>
          <aside class="col-md-4 blog-sidebar">
            <div class="p-3 mb-3 bg-light rounded">
            <h4 class="font-italic">Блоги</h4>
            <p class="mb-0">В разделе блогов публикую свои переводы статей, которые мне показались интересными. Приоритет - Ruby on Rails и Ruby. Планирую добавлять по одной статье каждую неделю.</p>
            </div>
            <div class="p-3">
            <h4 class="font-italic">Архив блогов</h4>
            <ol class="list-unstyled mb-0">
              <li><a href="<% @all_blogs.months_ago(2) %>">
                <%= month_human_name(1.month.ago.month) %> <%= 1.month.ago.year %></a></li>
              <li><a href="<% @all_blogs.months_ago(3) %>">
                <%= month_human_name(2.month.ago.month) %> <%= 2.month.ago.year %></a></li>
              <li><a href="<% @all_blogs.months_ago(4) %>">
                <%= month_human_name(3.month.ago.month) %> <%= 3.month.ago.year %></a></li>
              <li><a href="<% @all_blogs.months_ago(5) %>">
                <%= month_human_name(4.month.ago.month) %> <%= 4.month.ago.year %></a></li>
              <li><a href="<% @all_blogs.months_ago(6) %>">
                <%= month_human_name(5.month.ago.month) %> <%= 5.month.ago.year %></a></li>
              <li><a href="<% @all_blogs.months_ago(7) %>">
                <%= month_human_name(6.month.ago.month) %> <%= 6.month.ago.year %></a></li>
              <li><a href="<% @all_blogs.months_ago(8) %>">
                <%= month_human_name(7.month.ago.month) %> <%= 7.month.ago.year %></a></li>
              <li><a href="<% @all_blogs.months_ago(9) %>">
                <%= month_human_name(8.month.ago.month) %> <%= 8.month.ago.year %></a></li>
              <li><a href="<% @all_blogs.months_ago(10) %>">
                <%= month_human_name(9.month.ago.month) %> <%= 9.month.ago.year %></a></li>
              <li><a href="<% @all_blogs.months_ago(11) %>">
                <%= month_human_name(10.month.ago.month) %> <%= 10.month.ago.year %></a></li>
              <li><a href="<% @all_blogs.months_ago(12) %>">
                <%= month_human_name(11.month.ago.month) %> <%= 11.month.ago.year %></a></li>
              <li><a href="<% @all_blogs.months_ago(13) %>">
                <%= month_human_name(12.month.ago.month) %> <%= 12.month.ago.year %></a></li>
            </ol>
            </div>
            <div class="p-3 mb-3 bg-light rounded">
            <h4 class="font-italic">Первоисточник</h4>
            <p class="mb-0">Под заголовком каждого блога указан источник с именем автора и ссылкой на страницу с исходным текстом.</p>
            </div>
          </aside><!-- /.blog-sidebar -->
          </div><!-- /.row -->
        </div>
      </main><!-- /.container -->

    <footer class="footer bg-dark">
        <%= render 'shared/footer' %>
    </footer>
  </div>
  </body>
</html>

app/views/layouts/home.html.erb
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>Обо мне</title>
  </head>
  <body class="home">
    <%= render 'shared/nav_bar' %>
    <div id="background"></div>
    <div class="container d-flex justify-content-center h-100 p-3 mx-auto flex-column">
      <main role="main" class="inner cover">
        <%= yield %>
      </main>
    </div>
    <footer class="footer bg-dark">
      <%= render 'shared/footer' %>
    </footer>
  </body>
</html>

app/views/layouts/memo.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>Memo</title>
  </head>

  <body>


    <main role="main">

      <%= render @memos %>

    </main>

    <footer class="text-muted">
      <div class="container">
        <%= link_to 'New', new_memo_path %>
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
      </div>
    </footer>


  </body>
</html>

app/views/memos/_form.html.erb
<%= form_with model: @memo, local: true do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :memo %>
  <%= f.text_area :body, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.submit class: "btn btn-primary btn-lg" %>
</div>
<% end %>

app/views/memos/_memo.html.erb
	<div class="row">
		<div class="col-md-12">
			<div class="card-group" id="panel-352784">
				<div class="card">
					<div class="card-header">

            <%= link_to memo.title, "#panel-element-710237#{memo.id}", class: "card-title collapsed", "data-toggle": "collapse", "data-parent": "#panel-352784" %>
						 <!-- <a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-352784" href="#panel-element-710237">
               <%= memo.title %></a> -->

					</div>
					<div id="panel-element-710237<%= "#{memo.id}" %>" class="panel-collapse collapse">
						<div class="card-block">
							<%= memo.body %>
              <%= render partial: 'memo_links', locals: { memo: memo} %>
						</div>
					</div>
				</div>
			</div><br>
		</div>
	</div>
	

app/views/memos/_memo_links.html.erb
<p>
<%= link_to 'Edit', edit_memo_path(memo) %> |
<%= link_to 'Delete', memo_path(memo), method: :delete %>
</p>

app/views/memos/edit.html.erb
<h2>Edit Memo</h2>
<%= render 'form' %>
<%= link_to 'Back', memos_path %>

app/views/memos/index.html.erb
<h2>From memos index</h2>

app/views/memos/new.html.erb
<h2>New Memo</h2>
<%= render 'form' %>
<%= link_to 'Back', memos_path %>

app/views/page/about.html.erb
<h1 >Немного о себе</h1>
<div class="row">
  <div class="col md-4" style="text-align:left">
  <%= image_tag "http://via.placeholder.com/200x300", width: 200, alt: 'profile image', class: "about-img" %>

    <p>Фамилия: Казанцев</p>
    <p>Имя: Владимир</p>
    <p>Отчество: Петрович</p>
    <p>Родился 8 мая 1970г. в городе Владивостоке, где сейчас и проживаю. В 1996г. окончил Дальневосточный Государственный универститет с дипломом переводчика японского языка. Работал в судоходных компаниях, занимался автомобильным бизнесом и поставками автозапчастей из Японии.</p>
    <p>В 2017г. увлекся разработкой приложений на Ruby и Ruby on Rails. В настоящее время прохожу обучение в онлайн-школе <%= link_to 'Tninknetica', "http://thinknetica.com", target: '_blank' %>. Дополнительно изучаю курсы Джордана Хадженса на <%= link_to 'Udemy.com', "https://www.udemy.com/professional-rails-5-development-course/", target: '_blank' %>. </p>
    <p>Хорошо владею японским и английским языками, учу испанский.
    </p>

  </div>
</div>

app/views/page/contact.html.erb
<h1 class="cover-heading">Контакты</h1>
<p>
  Email: bb1667@ya.ru
</p>
<p>Skype: kaz.vl
</p>

app/views/portfolios/_form.html.erb
<%= form_with model: @portfolio, local: true do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :subtitle %>
  <%= f.text_area :subtitle, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :text %>
  <%= f.text_area :body, rows: 10, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.submit class: "btn btn-primary btn-lg" %>
</div>
<% end %>

app/views/portfolios/_portfolio.html.erb
  <!-- <td>
    <%= link_to portfolio.title, portfolio_path(portfolio) %><br>
    <%= portfolio.subtitle %><br>
    <%= image_tag portfolio.thumb_img unless portfolio.thumb_img.nil? %>
  </td> -->
  <div class="col-md-4">
    <div class="card mb-4 box-shadow">
      <%= image_tag portfolio.thumb_img, class: "card-img-top" %>
      <div class="card-body">
        <p class="card-text"><%= portfolio.title %></p><p><%= portfolio.subtitle %></p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <%= link_to 'Просмотр', portfolio_path(portfolio), class: "btn btn-sm btn-outline-secondary" %>
            <%#= link_to 'Edit', edit_portfolio_path(portfolio), class: "btn btn-sm btn-outline-secondary" %>
            <%#= link_to 'Delete', portfolio_path(portfolio), action: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-sm btn-outline-secondary" %>
            <%= link_to 'GitHub', "https://github.com", target: "_blank", class: "btn btn-sm btn-outline-secondary" %>
          </div>
          <small class="text-muted">
            <%= time_ago_in_words(portfolio.created_at) %> ago
          </small>
        </div>
      </div>
    </div>
  </div>

app/views/portfolios/edit.html.erb
<h2>Edit Portfolio</h2>
<%= render 'form' %>
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/index.html.erb
<h2>Portfolio</h2>
<table>
    <tbody>
      <tr>
  <%= render @portfolios %>
</tr>
    </tbody>

</table><br>
<%= link_to 'Create new', new_portfolio_path %>

app/views/portfolios/new.html.erb
<h2>New Portfolio</h2>
<%= render 'form' %><br>
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/show.html.erb
<h2>Portfolio <%= @portfolio.id %></h2>
<%= @portfolio.title %>
<p><%= @portfolio.subtitle %></p>
<p><%= @portfolio.body %></p>
<p><%= image_tag @portfolio.main_img unless @portfolio.main_img.nil? %></p><br>
<%= link_to 'Back', portfolios_path %> |
<%= link_to 'Edit', edit_portfolio_path(@portfolio) %> |
<%= link_to 'Delete', portfolio_path(@portfolio), method: :delete, data: { confirm: "Are you sure?"} %>
<br>

app/views/shared/_footer.html.erb
<%= year %> Владимир Казанцев
<span class="fa-lg">
  <a href="#"><%= fa_stacked_icon "github inverse", base: "circle" %></a>
  <a href="#"><%= fa_stacked_icon "facebook inverse", base: "circle" %></a>
  <a href="#"><%= fa_stacked_icon "twitter inverse", base: "circle" %></a>
  <a href="#"><%= fa_stacked_icon "vk inverse", base: "circle" %></a>
  <a href="#"><%= fa_stacked_icon "telegram inverse", base: "circle" %></a>
  <a href="#"><%= fa_stacked_icon "skype inverse", base: "circle" %></a>
</span>

app/views/shared/_nav_bar.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">О чем этот сайт</h4>
          <p class="text-muted">В разделе блогов публикую свои переводы интересных статей. В разделе Портфолио - мои проекты, пока совсем мало. В разделе "Заметки" собраны шпаргалки по настройкам различных гемов и системы в целом.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Контакты</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Skype</a></li>
            <li><a href="#" class="text-white">Facebook</a></li>
            <li><a href="#" class="text-white">Email</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<div class="navbar navbar-dark bg-dark box-shadow">
  <div class="container d-flex justify-content-between">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <nav class="nav-links">

      <%= link_to 'Блог', blogs_path %>
      <%= link_to 'Портфолио', portfolios_path %>
      <%= link_to 'Заметки', memos_path %>
      <%= link_to 'Обо мне', root_path %>
      <%= link_to 'Контакты', page_contact_path %>

    </nav>
    
  </div>
</div>
</header>

app/views/skills/_skill.html.erb
<p><%= skill.title %></p>
<p><%= image_tag skill.badge, width: 81 %></p>
<p><%= skill.percent %></p>

app/views/skills/index.html.erb
<%= render @skills %>
<p>
<%= link_to "New", new_skill_path %> 

</p>